project:
  type: website

website:
  title: "Business Entry Rates"
  navbar:
    left:
      - href: index.qmd
      - index2.qmd
      - model.qmd
      - sources.qmd
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



